import 'package:hive_flutter/hive_flutter.dart';
import 'package:task_manager/domain/entities/task.dart';

part 'task_model.g.dart';

/// Task model for data layer (Hive storage)
/// This model will be generated by Hive to create adapters
@HiveType(typeId: 0)
class TaskModel extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String title;

  @HiveField(2)
  late String? description;

  @HiveField(3)
  late DateTime? dueDate;

  @HiveField(4)
  late int priorityIndex; // 0=low, 1=medium, 2=high

  @HiveField(5)
  late bool isCompleted;

  @HiveField(6)
  late DateTime createdAt;

  @HiveField(7)
  late DateTime updatedAt;

  TaskModel({
    required this.id,
    required this.title,
    this.description,
    this.dueDate,
    required this.priorityIndex,
    required this.isCompleted,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Convert TaskModel to Task entity
  Task toEntity() {
    return Task(
      id: id,
      title: title,
      description: description,
      dueDate: dueDate,
      priority: Priority.values[priorityIndex],
      isCompleted: isCompleted,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  /// Create TaskModel from Task entity
  factory TaskModel.fromEntity(Task task) {
    return TaskModel(
      id: task.id,
      title: task.title,
      description: task.description,
      dueDate: task.dueDate,
      priorityIndex: task.priority.index,
      isCompleted: task.isCompleted,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
    );
  }

  /// Create a copy with modified fields
  TaskModel copyWith({
    String? id,
    String? title,
    String? description,
    DateTime? dueDate,
    int? priorityIndex,
    bool? isCompleted,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return TaskModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      priorityIndex: priorityIndex ?? this.priorityIndex,
      isCompleted: isCompleted ?? this.isCompleted,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() =>
      'TaskModel(id: $id, title: $title, priorityIndex: $priorityIndex, isCompleted: $isCompleted)';
}
